version: '3.8'

services:
  be:
    build:
      context: .
      dockerfile: BE/Dockerfile
    image: prototype-be:latest
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  fe:
    build:
      context: .
      dockerfile: FE/Dockerfile
      args:
        VITE_MAIN_URL: "http://54.254.136.203:4000"
    image: prototype-fe:latest
    ports:
      - "5173:80"
    depends_on:
      - be
    environment:
      - VITE_MAIN_URL=http://54.254.136.203:4000
    restart: unless-stopped
